apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
commonLabels:
  app: tekton-e2e
  app.kubernetes.io/instance: tekton-e2e
  app.kubernetes.io/name: tekton-e2e
